### ISSUE TITLE
Example Doesn't Work

### ISSUE THREAD

**Issue by 0Vipin0** [mdazharuddin1011999/UPI-Plugin-Flutter#1]
If I simply change the UpiIndiApps.PhonePe to UpiIndiaApps.PayTm then the app simply broke down and exit.

**Comment by azhar1038** [comment]
Try writing UpiIndiaApps.PayT**M**.

**Comment by 0Vipin0** [comment]
I have done that but still no use. App crashes anytime I click on the pay button.
I think you should use some kind of exception handling in case any error happens.

**Comment by azhar1038** [comment]
I just downloaded PayTM and the example did actually crashed. It happens because PayTM is not ready to accept the payment i.e. I wasn't logged in. After registration it works fine. I will try to add some exception handling in the plugin for this issue. Thanks for letting me know about this issue.

**Comment by 0Vipin0** [comment]
I have also tested the other options. TrueCallerUpi is also crashing when button clicked and the airtelpaymentupi shows error after opening the app.

**Comment by azhar1038** [comment]
Well I have updated the plugin. It was working fine in my case. I have tested it with all the apps (some ready to accept while some not). In case you see error again, write the error in comment.
