### ISSUE TITLE
It is not able to detect apps like paytm, airtel pay etc

### ISSUE THREAD

**Issue by Dhruv245** [mdazharuddin1011999/UPI-Plugin-Flutter#10]
The plugin is not able to auto detect apps like paytm and airtel pay . But is able to detect apps like imobile, sharit, makemytrip, bhmi

**Comment by Dhruv245** [comment]
![WhatsApp Image 2020-05-29 at 9 33 10 PM](https://user-images.githubusercontent.com/52127829/83280322-1daa1780-a1f4-11ea-9fd8-0881fc4194d8.jpeg)

**Comment by azhar1038** [comment]
Are you sure the apps that are not shown are **ready** to accept payment request. I mean are you logged in to those apps and are able to use it to make payments?

If yes, can you try using predefined package name like UpiApp.PayTM and comment what happens.

**Comment by Dhruv245** [comment]
yes, I have login in them

**Comment by Dhruv245** [comment]
Can you tell me the whole code to register a single app

**Comment by azhar1038** [comment]
When calling startTransaction provide UpiApp.PayTM in app parameter.

```dart
Future<UpiResponse> initiateTransaction(String app) async {
    return _upiIndia.startTransaction(
      app: UpiApp.PayTM,
      receiverUpiId: '9078600498@ybl',
      receiverName: 'Md Azharuddin',
      transactionRefId: 'TestingUpiIndiaPlugin',
      transactionNote: 'Not actual. Just an example.',
      amount: 1.00,
    );
  }
```
And comment what happens.

**Comment by Dhruv245** [comment]
It is only showing loading
Nothing is happening

**Comment by Dhruv245** [comment]
Can you tell me the issue

**Comment by azhar1038** [comment]
Most probably PayTM is unable to process the request. I am looking into it. In the mean time you can also study the source code to look what may be causing this problem.

**Comment by azhar1038** [comment]
Paytm is shown in the list
![Screenshot_2020-05-30-12-46-59-385_com az upi_india_example](https://user-images.githubusercontent.com/42082172/83322262-cba8d680-a273-11ea-8f97-d6b2f6bbde7a.jpg)

**Comment by azhar1038** [comment]
And is also able to handle the request. Are you sure it is not working.
![Screenshot_2020-05-30-12-49-29-674_net one97 paytm](https://user-images.githubusercontent.com/42082172/83322311-28a48c80-a274-11ea-929a-71d45e6d827d.jpg)

Can you share a screen recording of the problem?

**Comment by azhar1038** [comment]
When I log out of paytm, it is not shown in list. But when I am logged in, it is working fine as expected.

**Comment by Dhruv245** [comment]
I am using the code that you have used in github examples

**Comment by azhar1038** [comment]
I am also using the same one.

**Comment by azhar1038** [comment]
Can you give a screen recording of the problem you are facing as I am unable to reproduce the issue.

**Comment by Dhruv245** [comment]
does dual apps create this issue

**Comment by Dhruv245** [comment]
or it is because the paytm no I am using is not the same as the phone no in my mobile phone

**Comment by azhar1038** [comment]
No phone number shouldn't be a problem. I don't know about the dual apps.

**Comment by Dhruv245** [comment]
I dont know how but Google pay is now working but paytm is not

**Comment by azhar1038** [comment]
What do you mean by **not working**? Is it not shown in the list or is not handling the payment?

**Comment by Dhruv245** [comment]
Paytm is not showing in the list

**Comment by azhar1038** [comment]
See the list is returned by the package manager itself. All I am doing is passing the data from android platform to flutter part.

What happens when you directly invoke PayTM using:
```dart
Future<UpiResponse> initiateTransaction(String app) async {
    return _upiIndia.startTransaction(
      app: UpiApp.PayTM,
      receiverUpiId: '9078600498@ybl',
      receiverName: 'Md Azharuddin',
      transactionRefId: 'TestingUpiIndiaPlugin',
      transactionNote: 'Not actual. Just an example.',
      amount: 1.00,
    );
  }
```

**Comment by j33tmane** [comment]
In my case it was sowhing shareit in list (Listed 4 apps only)
I uninstalled shareit app  then next time Paytm is listed(its completely random listing but still )
i would suggest try uninstalling any one app listed in your getAllUpiApps call.
Check this issue #12

**Comment by azhar1038** [comment]
@Dhruv245  are you seeing the same thing as mentioned by @j33tmane ?
