### ISSUE TITLE
It is based on UPI

### ISSUE THREAD

**Issue by shagilsiddiqui** [mdazharuddin1011999/UPI-Plugin-Flutter#11]
will this plugin work in the UK?
As it is based on UPI.

**Comment by azhar1038** [comment]
UPI is only for India. UPI doesn't support any currency other than INR till now. Take a look at page 5 last line: [Upi Link specifications](https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf)

If you want to use similar plugin for your country, fork it and modify according to your requirements.
