### ISSUE TITLE
Showing only first 4 apps

### ISSUE THREAD

**Issue by j33tmane** [mdazharuddin1011999/UPI-Plugin-Flutter#12]
I am getiing only 4 application in available list..
i have more than 4 upi feature apps and which are supported by this package.
When i uninstall any one of previously showing app next time new app is listed but only 4 apps are geting listed in below call

```dart
_upiIndia.getAllUpiApps().then((value) {
    setState(() {
      apps = value;
    });
  });
```

> upi india V 2.1.2

**Comment by azhar1038** [comment]
I will look into this problem.

**Comment by j33tmane** [comment]
Ok, Thanks for quick reply. Waiting for your next update/reply..

**Comment by azhar1038** [comment]
I have modified the plugin little bit. Take a look at this:<br><br>
<img src="https://user-images.githubusercontent.com/42082172/84231152-1eec1600-ab0b-11ea-9c8b-ef35d3d387ce.jpg" alt="success">
I haven't uploaded it to pub.dev yet. You can fork or clone the repo and test the example itself to see it. I don't think it will solve your problem though.

The [Code](https://github.com/mdazharuddin1011999/UPI-Plugin-Flutter/blob/master/android/src/main/java/com/az/upi_india/UpiIndiaPlugin.java) that I have written depends on the package manager of the device to return the apps that can handle the upi request generated by this plugin as an intent call. So I can't say why you are only seeing 4 apps.

Anyway now I can guarantee that if an app is listed then it will be able to process the request and you can assume the UPI apps that are not shown won't even be able to process the payment request generated by this plugin.

I don't know if it helps you but that is the most I can do without reproducing the issue itself.

If you want to help me, try using another plugin [upi_pay](https://pub.dev/packages/upi_pay). It also offers the same feature but has been implemented in Kotlin. If it is able to list all the apps that you have, please comment it here.

Thanks in advance.
