### ISSUE TITLE
startTransaction() not returning anything

### ISSUE THREAD

**Issue by pranayfating** [mdazharuddin1011999/UPI-Plugin-Flutter#14]
when I implement the given example in a new app then it is working fine but when I implement it in an already released app(I want to update this app with your plugin) then the _upiIndia.startTransaction() is not returning anything(even not returning null). Please look at it. I need urgent help.

```dart
_upiIndia.startTransaction(
      app: app,
      receiverUpiId: 'upi_id',
      receiverName: 'name',
      transactionRefId: 'TestingUpiIndiaPlugin',
      transactionNote: 'Not actual. Just an example.',
      amount: 1.00,
    );
```

**Comment by azhar1038** [comment]
Is it able to open the requested UPI app? Which UPI apps have you tried?

**Comment by pranayfating** [comment]
I tried Google pay, Paytm, and Phonepe. Yes, the app is opening but after that even if the transaction is successful it is not returning anything.

**Comment by azhar1038** [comment]
> when I implement the given example in a new app then it is working fine but when I implement it in an already released app(I want to update this app with your plugin) then the _upiIndia.startTransaction() is not returning anything(even not returning null).

Did you mean is it working in debug mode but not in release mode?

**Comment by pranayfating** [comment]
I have signed the app and have already released the app. Now I'm debugging it for the next update.

**Comment by azhar1038** [comment]
Signing an app won't make any difference. If it is not working even in debug mode then maybe you haven't implemented it properly or it conflicts with any other plugin that you are using in your app. So I would recommend you to either clone and edit the repo to fit your requirement or try using any other plugin available in pub.

I am unable to reproduce your issue on my side. It is working fine even with a signed app.

**Comment by kjdeepak** [comment]
I am facing the same issue! The   initiateTransaction(app.app); not returning anything! Tried for google pay, HDFC Bank and BHIM app

**Comment by azhar1038** [comment]
Maybe the plugin is conflicting with any other plugin that you are using in your app. I tested the plugin on 16/07/2020 and it was working. Try using any other plugin or try writing your own taking reference from this plugin.

**Comment by pranayfating** [comment]
> I am facing the same issue! The initiateTransaction(app.app); not returning anything! Tried for google pay, HDFC Bank and BHIM app

The issue in my case was this plugin was conflicting with the razorpay plugin. As soon as I removed the razorpay plugin everything worked fine.

**Comment by azhar1038** [comment]
Believe it or not I created this plugin only because the plugin that existed before was conflicting with google_sign_in and I needed both.

**Comment by kjdeepak** [comment]
> > I am facing the same issue! The initiateTransaction(app.app); not returning anything! Tried for google pay, HDFC Bank and BHIM app
> 
> The issue in my case was this plugin was conflicting with the razorpay plugin. As soon as I removed the razorpay plugin everything worked fine.

What changes should I make in this plugin so I can keep both razorpay and this plugin. I am new to flutter and have zero knowdlege on java. 
@pranayfating  A link or some external resource would be helpful.

@mdazharuddin1011999 
Apologies if this is not the right channel to ask help.

**Comment by azhar1038** [comment]
I don't know what changes you should make. I made this plugin from zero and it worked fine for me. I don't what causes the conflicts. Anyway if you are using razorpay, you won't need this plugin I guess.

**Comment by kjdeepak** [comment]
> I don't know what changes you should make. I made this plugin from zero and it worked fine for me. I don't what causes the conflicts. **Anyway if you are using razorpay, you won't need this plugin I guess.**

Unfortunately my project requirement needs both. The admin will enable or disable certain payment option from backend through api.

**Comment by metro636** [comment]
Modify razor pay plugin to return false if request code is not razorpay request code in Activity result
