### ISSUE TITLE
phonePay , AmazonPay not working

### ISSUE THREAD

**Issue by rinujacobthomas** [mdazharuddin1011999/UPI-Plugin-Flutter#17]
D/UpiIndia NOTE: (16488): Received NULL, User cancelled the transaction.
I/flutter (16488): UPI_INDIA_FINAL_RESPONSE: user_canceled
I/flutter (16488): Instance of 'UpiResponse'
I/flutter (16488): null
I/flutter (16488): UPI_INDIA_FINAL_RESPONSE: null
I/flutter (16488): UPI_INDIA_FINAL_RESPONSE: invalid_parameters
I/flutter (16488): Instance of 'UpiResponse'
I/flutter (16488): null
 
both the transaction was successfull

**Comment by azhar1038** [comment]
If you are getting user cancelled, that means the requested app is not sending any data and if you are receiving invalid parameters then that app is unable to process your request.

I have tested the plugin in PhonePe, it works perfectly fine. Can't say about AmazonPay.

**Comment by rinujacobthomas** [comment]
getting response as user_canceled for phonePay.

**Comment by azhar1038** [comment]
Working on my side. So closing.
