### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by yashwp** [mdazharuddin1011999/UPI-Plugin-Flutter#20]
Hi,

I would like to know, when can we see the support for the iOS platform as well?

Thanks.

**Comment by azhar1038** [comment]
For that I will need a MacBook, knowledge in swift and ios app development. If you send me a MacBook, I will probably need 1 month to make it work in ios! Just kidding 🤣.

Anyway, I am adding help tag and if you want feel free to send a PR!

**Comment by azhar1038** [comment]
I did a quick research about intent calls in ios. It doesn't look promising. I don't know if it's even possible or not because this plugin is all about intents.

Anyway I have zero experience of working with ios, so can't say anything for sure. Maybe you can check if any other upi plugin supports ios.

**Comment by yashwp** [comment]
@mdazharuddin1011999 Same with me, no Apple device or experience with iOS development.

**Comment by reeteshranjan** [comment]
I worked with upi_pay package (https://github.com/drenther/upi_pay) developers on this as well as expanding overall support to what is a very wide spectrum of UPI payment apps. I chose that package as their maintenance seemed to be active (based on how recent their last release was). However; I'm more than happy to help each UPI package if their main developers have time and interest to keep working on continuously upgrading their project. So sharing details of work I did with upi_pay developers.

Feel free to look at these and let me know if you find it useful and worth integrating:

https://github.com/drenther/upi_pay/issues/15
https://github.com/drenther/upi_pay/issues/2
https://github.com/reeteshranjan/upi_pay (my fork of upi_pay with all the work I did committed)

**Comment by azhar1038** [comment]
Thanks for the information. I will look into the resources you have provided!

**Comment by reeteshranjan** [comment]
> Thanks for the information. I will look into the resources you have provided! Also it's not that I don't maintain this package, I just had no idea of what to improve 😅. Recently I have migrated this plugin to use v2 embedding as instructed in docs and wanted to test it but got busy in interview preparations. It's still in beta branch and I haven't pushed it to pub.
> 
> Anyway thanks a lot!

Thanks but there is no need to clarify your availability. What really matters is how active the project is. If it's not active, it's not your fault and I hope you have not taken my comment on this project's status personally. My intent was never that.

**Comment by azhar1038** [comment]
Wow! It seems you did quite a deep research. For now I will be focusing on integration of more UPI apps and keep iOS for later. I would be happy if you could help me in this.

**Comment by yashwp** [comment]
@reeteshranjan I would say, you can contribute here with iOS integration.

**Comment by reeteshranjan** [comment]
> @reeteshranjan I would say, you can contribute here with iOS integration.

I will. Been hectic unexpectedly and soon will contribute pull requests.

**Comment by reeteshranjan** [comment]
> Wow! It seems you did quite a deep research. For now I will be focusing on integration of more UPI apps and keep iOS for later. I would be happy if you could help me in this.

Pull requests soon

**Comment by reeteshranjan** [comment]
Please look at https://github.com/drenther/upi_pay/pull/17

**Comment by azhar1038** [comment]
Nice! But sadly I still have no means to test iOS stuff  : (

**Comment by reeteshranjan** [comment]
Then you can go with my testing, if that makes sense.😊 

I'm testing on iPhone 7 with iOS 14.x. With minimum iOS versions required for UPI moving upward all the time (my earlier iPhone 6 that won't upgrade beyond a certain iOS version blocked me from testing several apps that would just bail out on that phone), I guess iPhone 7 + iOS 14.x is the lowest combination to safely make UPI work anyway.

**Comment by azhar1038** [comment]
That would be great, thanks!

From what I understood, iOS will randomly call any available upi app for carrying out the payment. I don't know much about iOS but is this the default behaviour? I mean what if you have multiple browsers installed and you click on any link? Will it randomly choose any available browser to open the link?

**Comment by reeteshranjan** [comment]
> That would be great, thanks!
> 
> From what I understood, iOS will randomly call any available upi app for carrying out the payment. I don't know much about iOS but is this the default behaviour? I mean what if you have multiple browsers installed and you click on any link? Will it randomly choose any available browser to open the link?

Yes.

However; for the case of UPI apps, it's not completely random. Observation shows that iOS picks the oldest installed app. In all the testing so far, I see this behaviour consistently. I have properly highlighted this behaviour in the README, and every other important detail of how things work differently across Android and iOS.

About browsers, there is 'default browser' concept on Mac and iOS. That's picked. That one is not random at all.

**Comment by azhar1038** [comment]
Man! Learning iOS app development will be a hell lot difficult, I guess 😭

**Comment by reeteshranjan** [comment]
> Man! Learning iOS app development will be a hell lot difficult, I guess 😭

As difficult or easy as any other thing really. Everything comes with its pros and cons. For example, take your work on Android 11 break. That security aspect that you have to declare every app you want to call is there in iOS 8 onward (today it's iOS 14). Once you go through developing with that kind of framework, it makes you more aware about security and privacy. At the same time, not many will be happy with the Objective C syntax and the length of the code developed with it!! Swift has relaxed many iOS developers. The list of pros and cons just goes on.

**Comment by azhar1038** [comment]
True.

Actually according to docs there is no need of adding all apps in the manifest if you just declare the scheme but it didn't work, so I just added them.
