### ISSUE TITLE
pressing back button makes the transaction failed even when money was deducted.

### ISSUE THREAD

**Issue by ashutoshxhq** [mdazharuddin1011999/UPI-Plugin-Flutter#22]
Is there a way to check using the transaction id that the payment was success or not

**Comment by azhar1038** [comment]
How can payment succeed if you cancel it by pressing back button? I don't think there is a way to verify using transaction id without some bank consent.

**Comment by azhar1038** [comment]
If you are pressing back after initiating payment, ofcourse you won't receive the payment details.

**Comment by ashutoshxhq** [comment]
I saw that when I put in the UPI pin and initiated the payment and then pressed the back button, I received a transaction id but the status was failed. So is there some way to re fetch the transaction status.

**Comment by azhar1038** [comment]
No it doesn't work that way. All you can do is show a warning to not press back or something during transaction. Also this plugin is supposed to be used in small scale apps where you can provide manual customer support without getting involved with banks everytime. For bigger apps, I would suggest to use Razorpay or similar services.

**Comment by ashutoshxhq** [comment]
Got the idea @mdazharuddin1011999  Thanks for the help. I am closing this since I got what I was looking for.
