### ISSUE TITLE
Integration of more UPI apps

### ISSUE THREAD

**Issue by azhar1038** [mdazharuddin1011999/UPI-Plugin-Flutter#23]
**Thanks to [reeteshranjan](https://github.com/reeteshranjan) for his awesome and thorough research which can be [found in this discussion at upi_pay repository!](https://github.com/drenther/upi_pay/issues/15)**
## Features
* ~Removing URL encoding for parameter "pa"~
* ~Filter the list of received upi apps to remove to remove unsupported UPI apps~

## Check Working
\* Check mark represents that the behaviour of these apps have been double verified.
If you double check the behaviour of any of these apps, make sure to comment below and put a check mark!
**Verified Apps**
- [ ] All Bank
- [x] Amazon Pay
- [ ] Axis Pay
- [ ] Baroda Pay
- [x] BHIM
- [ ] Cent UPI
- [ ] Cointab
- [ ] Corp UPI
- [ ] DCB UPI
- [ ] Fino BPay
- [ ] Freecharge
- [x] Google Pay
- [ ] iMobile ICICI
- [ ] Indus Pay
- [ ] Khaali Jeb
- [ ] Maha UPI
- [ ] Mobikwik
- [ ] Oriental Pay
- [x] Paytm
- [ ] Paywiz
- [ ] PSB
- [ ] SBI Pay
- [ ] Yes Pay

**Apps not returning Transaction ID after payment**
- [x] MiPay (Play Store)
- [x] MiPay (GetApps)
- [ ] HSBC Simply Pay

**Non Verified Apps**
- [ ] True Caller
- [ ] BOI UPI
- [ ] CSB UPI
- [ ] CUB UPI
- [ ] digibank
- [ ] Equitas UPI
- [ ] Kotak
- [ ] PayZapp
- [ ] PNB
- [ ] RBL Pay
- [ ] realme PaySa
- [ ] United UPI Pay
- [ ] Vijaya UPI

**Unsupported Apps**
- [x] PhonePe  (Getting U16_NPCI_TXNRISK_00922)
- [x] Airtel Thanks
- [ ] AUPay
- [ ] Bandhan Bank UPI
- [ ] CANDI
- [ ] Indian Bank UPI
- [ ] Jet Pay
- [ ] KBL UPI
- [ ] KVB UPI
- [ ] LVB UPAAY
- [ ] Synd UPI
- [ ] UCO UPI
- [ ] Ultra Cash

**Comment by reeteshranjan** [comment]
@mdazharuddin1011999 it would be nice if you can give credit for original work by referring to the tickets/pull requests in upi_pay repo

**Comment by reeteshranjan** [comment]
Please look at https://github.com/drenther/upi_pay/pull/17

**Comment by azhar1038** [comment]
You mean add some flags like `merchant` or `experimental` to control which apps are returned by the `getAllUpiApps()`?

**Comment by reeteshranjan** [comment]
Yes. Please see the dartdoc generated docs I have already created for the existing flags `getAllUpiApps` in my latest commit supports (default behaviour is to give all properly working apps only that are listed in `APPS.md`).

As of now, I have not tested merchant payments. Working on a project where we are going to setup a merchant account, and then I would test again all the apps for merchant payments. Once that's done, there would be a flag for that as well.

**Comment by shashwatadi** [comment]
Hi @reeteshranjan and @azhar1038 Does this mean it is suitable for production using **verified Apps**?

**Comment by reeteshranjan** [comment]
> Hi @reeteshranjan and @azhar1038 Does this mean it is suitable for production using **verified Apps**?

Short answer: no.

Long answer: need more testing. With one person testing, there are lot of blockers. For example, daily transaction limit of either bank or UPI will be reached. So I would suggest developers interested in using `upi_pay` (this package still to get all the new work I have done) to participate in testing, and push results of what their observations are, so we have enough test data to qualify the package for production.
