### ISSUE TITLE
do you know how we can double check the transaction status ?

### ISSUE THREAD

**Issue by muhsinzyne** [mdazharuddin1011999/UPI-Plugin-Flutter#24]
Hi is there any UPI api for checking the recived payment status ????

**Comment by muhsinzyne** [comment]
i am wondering that how could we doble check the payment status and pamyent related information not other than just transaction id

**Comment by azhar1038** [comment]
Unfortunately, I don't think it's possible to fetch the transaction details using transactionID alone without keeping the records in your personal database. I don't think banks will make such information available so easily to public and is the reason why payment gateways exists. Maybe I am wrong but this is my conclusion.
