### ISSUE TITLE
How do I test the UPI payments?

### ISSUE THREAD

**Issue by pranav212000** [mdazharuddin1011999/UPI-Plugin-Flutter#25]

**Comment by azhar1038** [comment]
Can you please elaborate what do you want to test? If you mean Unit testing, I don't have much experience on that. Maybe you can create mock functions.

**Comment by pranav212000** [comment]
I mean the payment tests, Razorpay allows us to create virtual accounts and testing the functions using them but they don't support upi yet. Is there any other way to test the transfers?

**Comment by azhar1038** [comment]
No. Creating and testing with virtual id is not possible. If you want to test you can transfer ₹1 to some UPI Id and check manually if it's working.

**Comment by pranav212000** [comment]
Okay. Thanks!
