### ISSUE TITLE
How to send money using bank account instead of UPI ID?

### ISSUE THREAD

**Issue by dinesh4official** [mdazharuddin1011999/UPI-Plugin-Flutter#27]
Hi,

Thanks for the package. I need to transfer the money to my customers using bank account number and IFSC code instead UPI id. Can you let me know how to achieve this using this package.

Thanks in Advance,
Dinesh

**Comment by azhar1038** [comment]
This plugin is based on intent calls to UPI Apps following [NPCI UPI Linking Specification](https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf). So it's not possible for this plugin to send using bank account number. I would suggest you to go for any payment aggregators like RazorPay which is more secure and allows option other than UPI for payment.

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 thanks  but two week before. it was working perfect with the following format.

 receiverUpiId:
          "$accountNumber@$ifscNumber.ifsc.npci",

This week only it throws error as UpiIndiaInvalidParametersException (INVALID_PARAMETERS: Incorrect UPI ID provided)

**Comment by azhar1038** [comment]
Oh! It's because in the 2.2.0, I am using regex to verify the upi id. I didn't know about this hack! I will implement this as a feature if it really works. If it's urgent for you, you may switch back to stable version temporarily. Thanks for letting me know!

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 will give a try.. it may help for others..

**Comment by azhar1038** [comment]
You are right! It does work but not all UPI Apps can handle this like Mi Pay.

**Comment by azhar1038** [comment]
I have published the new version which supports passing bank account nuumber and IFSC code. [Check in pub](https://pub.dev/packages/upi_india/versions/2.2.0-dev.2)

You can use `getIdFromAccount(String accountNumber, String ifscCode)` method which does the extra work for you!

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 , thanks.  did you checked whether it is working at your end? Because, it is not working for the past week.

**Comment by azhar1038** [comment]
Yes. I was able to transfer. I tested the transaction through PhonePe only. Although Google Pay, PhonePe and BHIM, all were able to process the intent call.

**Comment by dinesh4official** [comment]
okay thanks i will give a try to this

**Comment by dinesh4official** [comment]
@mdazharuddin1011999  thanks, it navigates to the BHIM applications but the payment is always failed via my application.

**Comment by azhar1038** [comment]
Payment fails when using account number or even when using UPI ID? Are you sure it is not from bank side?

**Comment by dinesh4official** [comment]
yes, i am sure that it is not from bank side. I have done the same transaction from PhonePe instead via my application and the transaction is success.  Payment fails only when using account number. Bu two/three weeks back it works perfectly.

**Comment by azhar1038** [comment]
Maybe they can't process this type of transaction anymore. In my case PhonePe, Google Pay was able to complete the transaction while MiPay couldn't understand the request.

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 thanks
