### ISSUE TITLE
not geting a callback after payment is succes after inetegrated razorpay_flutter plugin

### ISSUE THREAD

**Issue by sonoo827** [mdazharuddin1011999/UPI-Plugin-Flutter#28]
Hi, 
i am facing issue in getting callback after succues payment,.. its working when i remove razorpay_flutter plugin or when i add this plugin then i dont recive any callback afert payment succes..but razorpay working sine..
. plz help  me.. thanks in advanced...

**Comment by azhar1038** [comment]
Can you try using the [dev version](https://pub.dev/packages/upi_india/versions/2.2.0-dev.2) and see if it still exists?

This happens when plugins confilts with each other. Check #14

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 , Am facing this issue without any gateway. In Redmi Note 7, am just initiating the transaction with updateing the UPI id  and other respective fields, and it navigates to the BHIM application like Phone Pe and Google Pay too but after the payment, no callback is received and then application starts booting from the scratch.

**Comment by dinesh4official** [comment]
This issue occurs only in Redmi Note 7 alone..

**Comment by dinesh4official** [comment]
@mdazharuddin1011999 , i using dev branch i.e., **upi_india: ^2.2.0-dev.1** and still issue replicates

**Comment by azhar1038** [comment]
That is something very specific and I dont't know why this is happening. Do you have any logs? What is the android version? What is the flutter version?

**Comment by dinesh4official** [comment]
![Android](https://user-images.githubusercontent.com/57437264/95328539-51dcc580-08c3-11eb-8687-e95f01fbe5a2.jpeg)


Nope, did n't have any logs.

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

**Comment by dinesh4official** [comment]
Flutter 1.23.0-7.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision db6e2d8aa5 (12 days ago) • 2020-09-25 06:47:03 -0400
Engine • revision 3a73d073c8
Tools • Dart 2.11.0 (build 2.11.0-161.0.dev)
