### ISSUE TITLE
Payment fails in PhonePe with U16_NPCI_TXNRISK_00922

### ISSUE THREAD

**Issue by dinesh4official** [mdazharuddin1011999/UPI-Plugin-Flutter#30]
Hi @mdazharuddin1011999 ,

When i tried to pay to my customer from my application via Phone Pe, it throws error as **u16 npci txn risk 00929** but in google pay it is working fine.

Same UPI id is working fine in PhonePe application.

Also, I noticed that the **transaction note** parameter fills the field in the Google Pay but not in Phone Pe..

` return upiIndia.startTransaction(
      app: upiApp,
      receiverId: upiId,
      receiverName: userName,
      transactionRefId: transactionId,
      transactionNote: 'User Payment',
      amount: actualamount,
    );`

i.e., User Payment -> transaction Note is reflected in the Google Pay transaction Note field but in PhonePe it fills with empty string(null).

Can you please check and share the details?

Flutter : 1.23.0-7.0.pre

**Comment by azhar1038** [comment]
Yes, you are right! Maybe they have made some changes to make their workflow more "Secure". It's from there side. Their is no mention of **U16_NPCI_TXNRISK_00922** in google.

They haven't provided any contacts either in their developers.phonepe site and hence I don't know what can I do.

**Comment by azhar1038** [comment]
Please refer this issue: #32
