### ISSUE TITLE
Google Pay Transaction error

### ISSUE THREAD

**Issue by airwind619** [mdazharuddin1011999/UPI-Plugin-Flutter#31]
Hi @mdazharuddin1011999 :

Google Pay throws: Payment failed **You have exceeded the maximum transaction amount set by your bank.**

Just tried running the sample code given.

**Comment by azhar1038** [comment]
Are you able to do the transaction directly from Google Pay?

**Comment by airwind619** [comment]
Ya bro

**Comment by vidhyesh** [comment]
I'm also have same issue please fix quickly

**Comment by azhar1038** [comment]
This isn't the issue of plugin. It's from their side. When I tested two days ago, it was working fine though. PhonePe has also made changes in their backend and transactions are failing #30

**Comment by vidhyesh** [comment]
> This isn't the issue of plugin. It's from their side. When I tested two days ago, it was working fine though.

Gpay and Phonepay both are not working that's why i thought the issue in library thanks for your replay :)

**Comment by airwind619** [comment]
Is their any way we could solve this issue?

**Comment by azhar1038** [comment]
I will take a look as soon as I can. But I doubt if can do anything regarding these matters.

Measures are being taken to make these payment related apps more secure and probably it's an effect of that.

Worst possible scenario would be to deprecate the plugin if all major UPI apps stops support or no workaround is found.

**Comment by azhar1038** [comment]
Please refer this issue: #32
