### ISSUE TITLE
Creating request amount transaction

### ISSUE THREAD

**Issue by clickervinod** [mdazharuddin1011999/UPI-Plugin-Flutter#33]
Hi,

Can we initiate a transaction for requesting amount to pay as the option shown in all UPI apps??

**Comment by azhar1038** [comment]
What do you mean by requesting amount?

**Comment by clickervinod** [comment]
by this I mean I can create a payment request and sen it to a specific UPI address and the user can approve it using entering upi pin and payment will be transferred from that user to me

**Comment by azhar1038** [comment]
What you are trying to do is possible but this plugin is NOT for this.

**Comment by ClickerVinod** [comment]
> What you are trying to do is possible but this plugin
Hi,
Can u share some references how to do this

**Comment by clickervinod** [comment]
Hi,
Can u share me some references to do this

**Comment by azhar1038** [comment]
Not sure but maybe you can use deep links to your app and add intent filters or maybe dynamic links

**Comment by clickervinod** [comment]
Thanks for your reply Can u share me latest UPI Specification document or
other docs so that I can explore it.

Thanks in Advance
