### ISSUE TITLE
The plugin `upi_india` requires your app to be migrated to the Android embedding v2.

### ISSUE THREAD

**Issue by vijayaselvam** [mdazharuddin1011999/UPI-Plugin-Flutter#34]
I cant use upi india as dependency. It shows migration error how to solve this issue.

**Comment by azhar1038** [comment]
That means your Flutter application is created using older version of the Android
embedding (v1) which has been deprecated. You need to migrate your application to use v2 embedding plugins.

**Comment by azhar1038** [comment]
https://stackoverflow.com/questions/65018588/your-flutter-application-is-created-using-an-older-version-of-the-android-embedd

This may help.

**Comment by vijayaselvam** [comment]
Thank You For Your Quick Response. Regular Updates need. Thank You.
