### ISSUE TITLE
Error Handling without Future Builder

### ISSUE THREAD

**Issue by pratikbutani** [mdazharuddin1011999/UPI-Plugin-Flutter#35]
```
Future<UpiResponse> initiateTransaction(UpiApp app) async {
    return _upiIndia
        .startTransaction(
          app: app,
          receiverUpiId: "xxx@upi",
          receiverName: 'Xxxx Xxxxx',
          transactionRefId: "TEST" + DateTime.now().millisecond.toString(),
          transactionNote: myDescription,
          amount: finalAmount,
        )
        .then((_upiResponse) => showAlertDialog(context, _upiResponse))
    .catchError((onError){
      // What onError will return? 
    });
  }
```

How can I handle **catchError** without Future Builder?

**Comment by azhar1038** [comment]
What do you mean? You are catching the error, you decide what to do with it.

**Comment by pratikbutani** [comment]
I mean What **onError** will return there?

**Comment by azhar1038** [comment]
Any of these exception:

UpiIndiaAppNotInstalledException
UpiIndiaUserCancelledException
UpiIndiaNullResponseException
UpiIndiaInvalidParametersException
UpiIndiaActivityMissingException

**Comment by azhar1038** [comment]
If you want to know how to handle specific errors, check this: https://dart.dev/guides/libraries/futures-error-handling#handling-specific-errors
