### ISSUE TITLE
how can i integrate for flutter web?

### ISSUE THREAD

**Issue by gs74340** [mdazharuddin1011999/UPI-Plugin-Flutter#36]

**Comment by azhar1038** [comment]
No. The way this plugin was created, cannot be implemented for web.

**Comment by gs74340** [comment]
Any other method or other way available ?

**Comment by azhar1038** [comment]
Use payment gateways

**Comment by gs74340** [comment]
How can other websites are using upi payments without gateways?. Their might be a way available without payment gateways.

**Comment by azhar1038** [comment]
I don't think you can do that. As far as I know all use some kind of payment gateway may it be paytm, paypal or razorpay. If you want to create a complete payment solution yourself check this: https://stackoverflow.com/questions/2647430/building-a-complete-online-payment-gateway-like-paypal/2652309#2652309
