### ISSUE TITLE
Not getting list of upi apps on Android 11

### ISSUE THREAD

**Issue by imrishuroy** [mdazharuddin1011999/UPI-Plugin-Flutter#39]
This plugin is not working for android 11 devices. It will we very helpful if guys can fix that.
Thank You

**Comment by azhar1038** [comment]
What's the error you are getting?

**Comment by imrishuroy** [comment]
Thanks for helping me out

**Comment by imrishuroy** [comment]
> What's the error you are getting?

(https://raw.githubusercontent.com/imrishuroy/Images/c71958d30ee253858406175706eed27685e15a37/WhatsApp%20Image%202021-04-07%20at%203.32.52%20PM.jpeg)
Getting this error. I have 5 UPIs app still installed. Still it is not detecting any of them.
Thanks In Advance.

**Comment by azhar1038** [comment]
Can I know which upi apps do you have? Also what is your target sdk version?

**Comment by imrishuroy** [comment]
I have Bhim, Google Pay, Phone Pay, Paytm, Yono, Baroda Pay
Target Sdk version is 30
And Min Sdk version is 21

**Comment by azhar1038** [comment]
The problem was Android 11 introduced changes related to package visibility. For more information, [check the documentation](https://developer.android.com/about/versions/11/privacy/package-visibility). I have published the updated version.

**Comment by rahul69x** [comment]
You have to change Target Sdk version from 30 to 29. It will work.

**Comment by azhar1038** [comment]
I believe it works with latest version even if you target sdk 30

**Comment by phanindravarma412** [comment]
> This plugin is not working for android 11 devices. It will we very helpful if guys can fix that.
> Thank You

Is this issue was fixed for you ?

**Comment by shailendraweb8** [comment]
> I believe it works with latest version even if you target sdk 30

still not fixed.
