### ISSUE TITLE
updated version is also not working for google pay

### ISSUE THREAD

**Issue by shailendra-rajpoot** [mdazharuddin1011999/UPI-Plugin-Flutter#6]
when use google pay payment is success fully done but upi india final response
UPI_INDIA_FINAL_RESPONSE: user_canceled

**Comment by azhar1038** [comment]
Duplicate of #5

**Comment by azhar1038** [comment]
Can you try any other plugin like [Upi Pay](https://pub.dev/packages/upi_pay) and comment what happens in that case?
