### ISSUE TITLE
Google Pay is not accepting payment request

### ISSUE THREAD

**Issue by Chethansmash7** [mdazharuddin1011999/UPI-Plugin-Flutter#7]
Google pay crashes as soon as it is clicked when the code as per the example app is run:

Here is the screenshot of the error
![Screenshot_2020-05-20-13-32-06-104_com flutterapppay](https://user-images.githubusercontent.com/14990970/82421377-8bd93680-9a9e-11ea-9186-25c9cd9828d5.png)
![Screenshot_2020-05-20-13-34-29-668_com google android apps nbu paisa user](https://user-images.githubusercontent.com/14990970/82421584-d8bd0d00-9a9e-11ea-8c63-a342c1307e6c.png)

**Comment by azhar1038** [comment]
What is the error shown in terminal? Are you using a correct UPI ID?

**Comment by Chethansmash7** [comment]
> What is the error shown in terminal? Are you using a correct UPI ID?

Terminal,No error.Yeah I used my own UPI ID,but as soon as I click on Google pay it crashes

**Comment by azhar1038** [comment]
Make sure that the UPI Id that you are using is not the same with which you are logged in to your GPay. I mean you cannot send money to yourself. Same goes for other UPI apps PhonePe, BHIM etc. Sometimes Server error can also cause that issue. Also make sure that GPay is able to make payment.

**Comment by azhar1038** [comment]
Check the newer version. The gif shows that plugin is working fine with GPay. Also if you switch to newer version, make sure to go through changelog. Name of classes have changed:

- **UpiIndiaApp** has been renamed to **UpiApp**
- **UpiIndiaResponse** has been renamed to **UpiResponse**
- **UpiIndiaResponseStatus** has been renamed to **UpiPaymentStatus**
- **UpiIndiaResponseError** has been renamed to **UpiError**

**Comment by azhar1038** [comment]
Any update? Are you still facing the problem?

**Comment by azhar1038** [comment]
So now I assume that you were using incorrect UPI id because of which GPay was not processing your payment request and so I am closing the issue now. Feel free to reopen the issue if you think I am incorrect.
