### ISSUE TITLE
Consider changing UpiIndia* to UPI*

### ISSUE THREAD

**Issue by HemilTheRebel** [mdazharuddin1011999/UPI-Plugin-Flutter#8]
UpiResponseStatus feels a lot more concise than UpiIndiaResponseStatus, etc.

**Comment by azhar1038** [comment]
I was planning to the same for quite some time. Today I have published a new version with modified class name:
- **UpiIndiaApp** has been renamed to **UpiApp**
- **UpiIndiaResponse** has been renamed to **UpiResponse**
- **UpiIndiaResponseStatus** has been renamed to **UpiStatus**
- **UpiIndiaResponseError** has been renamed to **UpiError**

**Comment by HemilTheRebel** [comment]
How about paymentstatus instead of upi status? I know it breaks consistency but it makes a lot more sense. Or maybe upipaymentstatus?

**Comment by azhar1038** [comment]
Check Version-2.1.2. I renamed **UpiStatus** to **UpiPaymentStatus**. Thanks for your suggestion.
