### ISSUE TITLE
Readme in pub.dev is not displaying the images

### ISSUE THREAD

**Issue by azhar1038** [mdazharuddin1011999/UPI-Plugin-Flutter#9]
![success](https://user-images.githubusercontent.com/42082172/82893023-1245ba80-9f6e-11ea-868d-a55062d34086.jpg)
![show](https://user-images.githubusercontent.com/42082172/82893565-d3643480-9f6e-11ea-96a7-493181df6214.gif)

**Comment by mdazharuddin1011999** [comment]
![success](https://user-images.githubusercontent.com/42082172/82893023-1245ba80-9f6e-11ea-868d-a55062d34086.jpg)
![show](https://user-images.githubusercontent.com/42082172/82893565-d3643480-9f6e-11ea-96a7-493181df6214.gif)

**Comment by azhar1038** [comment]
Solved using Github CDN by uploading them to comment and getting the link

**Comment by azhar1038** [comment]
Modified image 

![PicsArt_10-03-08 20 47](https://user-images.githubusercontent.com/42082172/94981672-b4dffc80-0551-11eb-821b-a3adb7f7a62f.jpg)
